config/routes.rb
Rails.application.routes.draw do

  # get 'api/v1/spellbooks/#/recipes/#'
  # get 'api/v1/recipes/#/ingredients/#'
  # get 'api/v1/containers/#/ingredients/#'
  # get 'api/v1/ingredients'
  # get 'api/v1/intruders'
  # get 'api/v1/customers'
  # get 'api/v1/witches'
  # get 'api/v1/familiars'

  scope 'api/v1' do 
    resources :spellbooks, only: [:show, :index] do
        resources :recipes, only: [:show, :index]
    end
    resources :recipes, only: [:show, :index] do
      resources :ingredients, only: [:show, :index]
    end
    resources :containers, only: [:show, :index]  do
      resources :ingredients, only: [:show, :index]
    end
    resources :ingredients, only: [:show, :index]
    resources :intruders, only: [:show, :index]
    resources :customers, only: [:show, :index]
    resources :witches, only: [:show, :index]
    resources :familiars, only: [:show, :index]
  end



  # Admin disabled because it's not needed and it's slowing
  # down development
  ##resources :admin do
  # get 'admin', to:'admin#index'
  # scope 'admin' do
  #   resources :spellbooks
  #   resources :recipes
  #   resources :containers
  #   resources :ingredients
  #   resources :intruders
  #   resources :customers
  #   resources :witches
  #   resources :familiars
  # end

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/familiar.rb
class Familiar < ApplicationRecord
end

app/controllers/familiars_controller.rb
class FamiliarsController < ApplicationController
  before_action :set_familiar, only: [:show, :edit, :update, :destroy]

  # GET /familiares
  # GET /familiares.json
  def index
    @models = Familiar.all
    @headers = @models[0].attributes.keys unless @models[0].nil?
    respond_to do |format|
      format.html {render :template => '_shared/common_index'}
      format.json {render @models}

    end
  end

  # GET /familiares/1
  # GET /familiares/1.json
  def show
    @model = Familiar.find(params[:id]) # ... or whatever here
    respond_to do |format|
      format.html {render :template => '_shared/common_show'}
      format.json { render :show, location: @model}
    end

  end

  # GET /familiars/new
  def new
    @familiar = Familiar.new
  end

  # GET /familiars/1/edit
  def edit
    @model = Familiar.find(params[:id]) # ... or whatever here
    render :template => '_shared/common_edit_form'
  end

  # POST /familiars
  # POST /familiars.json
  def create
    @familiar = Familiar.new(familiar_params)

    respond_to do |format|
      if @familiar.save
        format.html { redirect_to @familiar, notice: 'Familiar was successfully created.' }
        format.json { render :show, status: :created, location: @familiar }
      else
        format.html { render :new }
        format.json { render json: @familiar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /familiars/1
  # PATCH/PUT /familiars/1.json
  def update
    respond_to do |format|
      if @familiar.update(familiar_params)
        format.html { redirect_to @familiar, notice: 'Familiar was successfully updated.' }
        format.json { render :show, status: :ok, location: @familiar }
      else
        format.html { render :edit }
        format.json { render json: @familiar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /familiars/1
  # DELETE /familiars/1.json
  def destroy
    @familiar.destroy
    respond_to do |format|
      format.html { redirect_to familiars_url, notice: 'Familiar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_familiar
      @familiar = Familiar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def familiar_params
      params.require(:familiar).permit(:name, :tooltip, :description, :img_url, :element, :origin, :speed, :memory, :disicpline, :distracted_by)
    end
end

app/helpers/familiars_helper.rb
module FamiliarsHelper
end

app/views/familiars/_form.html.erb
<%= form_with(model: familiar, local: true) do |form| %>
  <% if familiar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(familiar.errors.count, "error") %> prohibited this familiar from being saved:</h2>

      <ul>
      <% familiar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :familiar_name %>
  </div>

  <div class="field">
    <%= form.label :tooltip %>
    <%= form.text_field :tooltip, id: :familiar_tooltip %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :familiar_description %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url, id: :familiar_img_url %>
  </div>

  <div class="field">
    <%= form.label :element %>
    <%= form.text_field :element, id: :familiar_element %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :familiar_origin %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.text_field :speed, id: :familiar_speed %>
  </div>

  <div class="field">
    <%= form.label :memory %>
    <%= form.text_field :memory, id: :familiar_memory %>
  </div>

  <div class="field">
    <%= form.label :disicpline %>
    <%= form.text_field :disicpline, id: :familiar_disicpline %>
  </div>

  <div class="field">
    <%= form.label :distracted_by %>
    <%= form.text_field :distracted_by, id: :familiar_distracted_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/familiars/edit.html.erb
<h1>Editing Familiar</h1>

<%= render 'form', familiar: @familiar %>

<%= link_to 'Show', @familiar %> |
<%= link_to 'Back', familiars_path %>

app/views/familiars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Familiars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tooltip</th>
      <th>Description</th>
      <th>Img url</th>
      <th>Element</th>
      <th>Origin</th>
      <th>Speed</th>
      <th>Memory</th>
      <th>Disicpline</th>
      <th>Distracted by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @familiars.each do |familiar| %>
      <tr>
        <td><%= familiar.name %></td>
        <td><%= familiar.tooltip %></td>
        <td><%= familiar.description %></td>
        <td><%= familiar.img_url %></td>
        <td><%= familiar.element %></td>
        <td><%= familiar.origin %></td>
        <td><%= familiar.speed %></td>
        <td><%= familiar.memory %></td>
        <td><%= familiar.disicpline %></td>
        <td><%= familiar.distracted_by %></td>
        <td><%= link_to 'Show', familiar %></td>
        <td><%= link_to 'Edit', edit_familiar_path(familiar) %></td>
        <td><%= link_to 'Destroy', familiar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Familiar', new_familiar_path %>

app/views/familiars/new.html.erb
<h1>New Familiar</h1>

<%= render 'form', familiar: @familiar %>

<%= link_to 'Back', familiars_path %>

app/views/familiars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @familiar.name %>
</p>

<p>
  <strong>Tooltip:</strong>
  <%= @familiar.tooltip %>
</p>

<p>
  <strong>Description:</strong>
  <%= @familiar.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @familiar.img_url %>
</p>

<p>
  <strong>Element:</strong>
  <%= @familiar.element %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @familiar.origin %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @familiar.speed %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @familiar.memory %>
</p>

<p>
  <strong>Disicpline:</strong>
  <%= @familiar.disicpline %>
</p>

<p>
  <strong>Distracted by:</strong>
  <%= @familiar.distracted_by %>
</p>

<%= link_to 'Edit', edit_familiar_path(@familiar) %> |
<%= link_to 'Back', familiars_path %>