config/routes.rb
Rails.application.routes.draw do

  # get 'api/v1/spellbooks/#/recipes/#'
  # get 'api/v1/recipes/#/ingredients/#'
  # get 'api/v1/containers/#/ingredients/#'
  # get 'api/v1/ingredients'
  # get 'api/v1/intruders'
  # get 'api/v1/customers'
  # get 'api/v1/witches'
  # get 'api/v1/familiars'

  scope 'api/v1' do 
    resources :spellbooks, only: [:show, :index] do
        resources :recipes, only: [:show, :index]
    end
    resources :recipes, only: [:show, :index] do
      resources :ingredients, only: [:show, :index]
    end
    resources :containers, only: [:show, :index]  do
      resources :ingredients, only: [:show, :index]
    end
    resources :ingredients, only: [:show, :index]
    resources :intruders, only: [:show, :index]
    resources :customers, only: [:show, :index]
    resources :witches, only: [:show, :index]
    resources :familiars, only: [:show, :index]
  end



  # Admin disabled because it's not needed and it's slowing
  # down development
  ##resources :admin do
  # get 'admin', to:'admin#index'
  # scope 'admin' do
  #   resources :spellbooks
  #   resources :recipes
  #   resources :containers
  #   resources :ingredients
  #   resources :intruders
  #   resources :customers
  #   resources :witches
  #   resources :familiars
  # end

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/intruder.rb
class Intruder < ApplicationRecord
end

app/controllers/intruders_controller.rb
class IntrudersController < ApplicationController
  before_action :set_intruder, only: [:show, :edit, :update, :destroy]

  # GET /intruderes
  # GET /intruderes.json
  def index
    @models = Intruder.all
    @headers = @models[0].attributes.keys unless @models[0].nil?
    respond_to do |format|
      format.html {render :template => '_shared/common_index'}
      format.json {render @models}

    end
  end

  # GET /intruderes/1
  # GET /intruderes/1.json
  def show
    @model = Intruder.find(params[:id]) # ... or whatever here
    respond_to do |format|
      format.html {render :template => '_shared/common_show'}
      format.json { render :show, location: @model}
    end

  end

  # GET /intruders/new
  def new
    @intruder = Intruder.new
  end

  # GET /intruders/1/edit
  def edit
    @model = Intruder.find(params[:id]) # ... or whatever here
    render :template => '_shared/common_edit_form'
  end

  # POST /intruders
  # POST /intruders.json
  def create
    @intruder = Intruder.new(intruder_params)

    respond_to do |format|
      if @intruder.save
        format.html { redirect_to @intruder, notice: 'Intruder was successfully created.' }
        format.json { render :show, status: :created, location: @intruder }
      else
        format.html { render :new }
        format.json { render json: @intruder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intruders/1
  # PATCH/PUT /intruders/1.json
  def update
    respond_to do |format|
      if @intruder.update(intruder_params)
        format.html { redirect_to @intruder, notice: 'Intruder was successfully updated.' }
        format.json { render :show, status: :ok, location: @intruder }
      else
        format.html { render :edit }
        format.json { render json: @intruder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intruders/1
  # DELETE /intruders/1.json
  def destroy
    @intruder.destroy
    respond_to do |format|
      format.html { redirect_to intruders_url, notice: 'Intruder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intruder
      @intruder = Intruder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intruder_params
      params.require(:intruder).permit(:name, :description, :img_url, :wants, :fears)
    end
end

app/helpers/intruders_helper.rb
module IntrudersHelper
end

app/views/intruders/_form.html.erb
<%= form_with(model: intruder, local: true) do |form| %>
  <% if intruder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intruder.errors.count, "error") %> prohibited this intruder from being saved:</h2>

      <ul>
      <% intruder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :intruder_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :intruder_description %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url, id: :intruder_img_url %>
  </div>

  <div class="field">
    <%= form.label :wants %>
    <%= form.text_field :wants, id: :intruder_wants %>
  </div>

  <div class="field">
    <%= form.label :fears %>
    <%= form.text_field :fears, id: :intruder_fears %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/intruders/edit.html.erb
<h1>Editing Intruder</h1>

<%= render 'form', intruder: @intruder %>

<%= link_to 'Show', @intruder %> |
<%= link_to 'Back', intruders_path %>

app/views/intruders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Intruders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Img url</th>
      <th>Wants</th>
      <th>Fears</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intruders.each do |intruder| %>
      <tr>
        <td><%= intruder.name %></td>
        <td><%= intruder.description %></td>
        <td><%= intruder.img_url %></td>
        <td><%= intruder.wants %></td>
        <td><%= intruder.fears %></td>
        <td><%= link_to 'Show', intruder %></td>
        <td><%= link_to 'Edit', edit_intruder_path(intruder) %></td>
        <td><%= link_to 'Destroy', intruder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intruder', new_intruder_path %>

app/views/intruders/new.html.erb
<h1>New Intruder</h1>

<%= render 'form', intruder: @intruder %>

<%= link_to 'Back', intruders_path %>

app/views/intruders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @intruder.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @intruder.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @intruder.img_url %>
</p>

<p>
  <strong>Wants:</strong>
  <%= @intruder.wants %>
</p>

<p>
  <strong>Fears:</strong>
  <%= @intruder.fears %>
</p>

<%= link_to 'Edit', edit_intruder_path(@intruder) %> |
<%= link_to 'Back', intruders_path %>