config/routes.rb
Rails.application.routes.draw do

  # get 'api/v1/spellbooks/#/recipes/#'
  # get 'api/v1/recipes/#/ingredients/#'
  # get 'api/v1/containers/#/ingredients/#'
  # get 'api/v1/ingredients'
  # get 'api/v1/intruders'
  # get 'api/v1/customers'
  # get 'api/v1/witches'
  # get 'api/v1/familiars'

  scope 'api/v1' do 
    resources :spellbooks, only: [:show, :index] do
        resources :recipes, only: [:show, :index]
    end
    resources :recipes, only: [:show, :index] do
      resources :ingredients, only: [:show, :index]
    end
    resources :containers, only: [:show, :index]  do
      resources :ingredients, only: [:show, :index]
    end
    resources :ingredients, only: [:show, :index]
    resources :intruders, only: [:show, :index]
    resources :customers, only: [:show, :index]
    resources :witches, only: [:show, :index]
    resources :familiars, only: [:show, :index]
  end



  # Admin disabled because it's not needed and it's slowing
  # down development
  ##resources :admin do
  # get 'admin', to:'admin#index'
  # scope 'admin' do
  #   resources :spellbooks
  #   resources :recipes
  #   resources :containers
  #   resources :ingredients
  #   resources :intruders
  #   resources :customers
  #   resources :witches
  #   resources :familiars
  # end

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredientes
  # GET /ingredientes.json
  def index
    @models = Ingredient.all
    @headers = @models[0].attributes.keys unless @models[0].nil?
    respond_to do |format|
      format.html {render :template => '_shared/common_index'}
      format.json {render @models}

    end
  end

  # GET /ingredientes/1
  # GET /ingredientes/1.json
  def show
    @model = Ingredient.find(params[:id]) # ... or whatever here
    respond_to do |format|
      format.html {render :template => '_shared/common_show'}
      format.json { render :show, location: @model}
    end

  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
    @model = Ingredient.find(params[:id]) # ... or whatever here
    render :template => '_shared/common_edit_form'
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:recipe_id, :ingredient_id, :name, :tooltip, :description, :img_url, :element, :origin)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.text_field :recipe_id, id: :ingredient_recipe_id %>
  </div>

  <div class="field">
    <%= form.label :container_id %>
    <%= form.text_field :container_id, id: :ingredient_container_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ingredient_name %>
  </div>

  <div class="field">
    <%= form.label :tooltip %>
    <%= form.text_field :tooltip, id: :ingredient_tooltip %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :ingredient_description %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url, id: :ingredient_img_url %>
  </div>

  <div class="field">
    <%= form.label :element %>
    <%= form.text_field :element, id: :ingredient_element %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :ingredient_origin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Container</th>
      <th>Name</th>
      <th>Tooltip</th>
      <th>Description</th>
      <th>Img url</th>
      <th>Element</th>
      <th>Origin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.recipe %></td>
        <td><%= ingredient.container %></td>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.tooltip %></td>
        <td><%= ingredient.description %></td>
        <td><%= ingredient.img_url %></td>
        <td><%= ingredient.element %></td>
        <td><%= ingredient.origin %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @ingredient.recipe %>
</p>

<p>
  <strong>Container:</strong>
  <%= @ingredient.container %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Tooltip:</strong>
  <%= @ingredient.tooltip %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ingredient.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @ingredient.img_url %>
</p>

<p>
  <strong>Element:</strong>
  <%= @ingredient.element %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @ingredient.origin %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>