config/routes.rb
Rails.application.routes.draw do

  # get 'api/v1/spellbooks/#/recipes/#'
  # get 'api/v1/recipes/#/ingredients/#'
  # get 'api/v1/containers/#/ingredients/#'
  # get 'api/v1/ingredients'
  # get 'api/v1/intruders'
  # get 'api/v1/customers'
  # get 'api/v1/witches'
  # get 'api/v1/familiars'

  scope 'api/v1' do 
    resources :spellbooks, only: [:show, :index] do
        resources :recipes, only: [:show, :index]
    end
    resources :recipes, only: [:show, :index] do
      resources :ingredients, only: [:show, :index]
    end
    resources :containers, only: [:show, :index]  do
      resources :ingredients, only: [:show, :index]
    end
    resources :ingredients, only: [:show, :index]
    resources :intruders, only: [:show, :index]
    resources :customers, only: [:show, :index]
    resources :witches, only: [:show, :index]
    resources :familiars, only: [:show, :index]
  end



  # Admin disabled because it's not needed and it's slowing
  # down development
  ##resources :admin do
  # get 'admin', to:'admin#index'
  # scope 'admin' do
  #   resources :spellbooks
  #   resources :recipes
  #   resources :containers
  #   resources :ingredients
  #   resources :intruders
  #   resources :customers
  #   resources :witches
  #   resources :familiars
  # end

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/container.rb
class Container < ApplicationRecord
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy]

  # GET /containeres
  # GET /containeres.json
  def index
    @models = Container.all
    @headers = @models[0].attributes.keys unless @models[0].nil?
    respond_to do |format|
      format.html {render :template => '_shared/common_index'}
      format.json {render @models}

    end
  end

  # GET /containeres/1
  # GET /containeres/1.json
  def show
    @model = Container.find(params[:id]) # ... or whatever here
    respond_to do |format|
      format.html {render :template => '_shared/common_show'}
      format.json { render :show, location: @model}
    end

  end


  # GET /containers/new
  def new
    @model = Container.new
    render :template => '_shared/common_new'
  end

  # GET /containers/1/edit
  def edit
    @model = Container.find(params[:id]) # ... or whatever here
    render :template => '_shared/common_edit_form'
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(container_params)

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:name, :description, :img_url, :element, :origin)
    end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_form.html.erb
<%= form_with(model: container, local: true) do |form| %>
  <% if container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% container.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :container_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :container_description %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url, id: :container_img_url %>
  </div>

  <div class="field">
    <%= form.label :element %>
    <%= form.text_field :element, id: :container_element %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :container_origin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing Container</h1>

<%= render 'form', container: @container %>

<%= link_to 'Show', @container %> |
<%= link_to 'Back', containers_path %>

app/views/containers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Containers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Img url</th>
      <th>Element</th>
      <th>Origin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |container| %>
      <tr>
        <td><%= container.name %></td>
        <td><%= container.description %></td>
        <td><%= container.img_url %></td>
        <td><%= container.element %></td>
        <td><%= container.origin %></td>
        <td><%= link_to 'Show', container %></td>
        <td><%= link_to 'Edit', edit_container_path(container) %></td>
        <td><%= link_to 'Destroy', container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New Container</h1>

<%= render 'form', container: @container %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @container.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @container.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @container.img_url %>
</p>

<p>
  <strong>Element:</strong>
  <%= @container.element %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @container.origin %>
</p>

<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>